### ISSUE TITLE
Taxi Rank Does Nothing

### ISSUE THREAD

**Issue by KatieSuth** [KatieSuth/CSC3950-Simtersection#2]
There is an option to add a taxi rank to the cars, but it does not appear to do anything. It adds a taxi stop to the far right side of the screen that you have to zoom out to see, but no cars stop at it. The yellow and white cars with stripes are taxis, but they generate with or without the taxi rank enabled. They stop at the taxi stop, but they do not pick up any pedestrians.

**Comment by BinaryBlacksmith** [comment]
Any car with racing stripes is stopping beside the taxi stop, but only briefly. Nowhere near the amount of time to actually load a passenger. Also, pedestrians seem disproportionately fast compared to cars. Taxi's seem to spawn en masse, rather than sporadically as well.

**Comment by KatieSuth** [comment]
Taxis are also only spawning from the north

**Comment by BinaryBlacksmith** [comment]
What is the name of the rw location? Might not be a bad idea to see where the Taxi stops really are.

**Comment by BinaryBlacksmith** [comment]
Although the anti-science union across from the women's health center is laugh-worthy.

**Comment by BinaryBlacksmith** [comment]
Fixed stopping issue.
